### ISSUE TITLE
"java.lang.IllegalArgumentException: invalid URLPatternSpec" with a colon in a path segment

### ISSUE THREAD

**Issue by pab-atos** [eclipse-ee4j/exousia#37]
When running glassfish 7.0.8 / JDK17 with a deployed app (myApp.war),

"curl http://localhost:8080/myApp/lookup/foobar" works as expected (I get a 404, because foobar does not exist)

But "curl http://localhost:8080/myApp/lookup/foo:bar" (with a colon) gives a 503, and this error in server.log : 

```
  Authentication passed, but authorization failed.
java.lang.IllegalArgumentException: invalid URLPatternSpec
        at jakarta.security.jacc.URLPatternSpec.setURLPatternArray(URLPatternSpec.java:326)
        at jakarta.security.jacc.URLPatternSpec.<init>(URLPatternSpec.java:79)
        at jakarta.security.jacc.WebResourcePermission.<init>(WebResourcePermission.java:141)
        at org.glassfish.exousia.AuthorizationService.checkWebResourcePermission(AuthorizationService.java:450)
        at org.glassfish.exousia.AuthorizationService.checkWebResourcePermission(AuthorizationService.java:438)
        at com.sun.enterprise.security.web.integration.WebSecurityManager.hasResourcePermission(WebSecurityManager.java:261)
        at com.sun.web.security.RealmAdapter.invokeWebSecurityManager(RealmAdapter.java:1146)
        at com.sun.web.security.RealmAdapter.preAuthenticateCheck(RealmAdapter.java:423)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:415)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:529)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:503)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:75)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:121)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:562)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:503)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:292)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:188)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:425)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

This used to work with a previous version of glassfish (4.1, with JDK8 and myApp still using J2EE 6)

Browsing the code, I was surprised to find this in org/glassfish/exousia/AuthorizationService.java
```
    public boolean checkWebResourcePermission(HttpServletRequest request, Set<Principal> principals) {
        return checkPermission(
            new WebResourcePermission(
                getConstrainedURI(request),
                request.getMethod()),
                principals);
    }
```

It seems that the first param to the WebResourcePermission (with triggers URLPatternSpec parsing) is the actual URI given by the http client. I do not understand what this code is trying to do.

**Comment by zistrong** [comment]
I pushed a PR to resolve this issue.
https://github.com/eclipse-ee4j/exousia/pull/30

**Comment by arjantijms** [comment]
Resoled by #52
